# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

name: build and deploy Workbooks
resources:
 pipelines:
   - pipeline: Scripts
     source: 'scriptsCI'

trigger:
 paths:
   include:
     - Workbooks/*

stages:
- stage: build_workbooks

  jobs:
    - job: AgentJob
      pool:
       name: Azure Pipelines
       vmImage: 'vs2017-win2016'
      steps:
       - task: CopyFiles@2
         displayName: 'Copy Workbooks'
         inputs:
          SourceFolder: Workbooks
          TargetFolder: '$(Pipeline.Workspace)'
       - task: Files-Validator@1
         inputs:
           rootDir: '$(Pipeline.Workspace)/*.json'
           validateXML: false
           validateJSON: true
           validateYAML: false
           validatePS: false
       - task: PublishBuildArtifacts@1
         displayName: 'Publish Artifact: Workbooks'
         inputs:
          PathtoPublish: '$(Pipeline.Workspace)'
          ArtifactName: Workbooks

- stage: deploy_workbooks
  jobs:
    - job: AgentJob
      pool:
       name: Azure Pipelines
       vmImage: 'windows-2019'
      variables: 
      - group: Az connection settings
      steps:
      - download: current
        artifact: Workbooks
      - download: Scripts
        patterns: '*.ps1'
      - task: AzurePowerShell@4
        displayName: 'Create and Update Workbooks'
        inputs:
         azureSubscription: $(azureSubscription)
         ScriptPath: '$(Pipeline.Workspace)/Scripts/Scripts/CreateWorkbooks.ps1'
         ScriptArguments: '-SubscriptionId $(SubscriptionId) -ResourceGroup $(ResourceGroup) -Workspace $(Workspace) -WorkbooksFolder $(Pipeline.Workspace)/Workbooks'
         azurePowerShellVersion: LatestVersion
         pwsh: true

